export const API = "http://134.209.96.140"

export const STAFF_ACTIONS = {
    GET__STAFFS: "GET__STAFFS",
    GET_ONE_STAFF: "GET_ONE_STAFF",
    GET_POSITIONS: "GET_POSITIONS"
};

export const PRODUCT_ACTIONS = {
    GET_PRODUCTS: "GET_PRODUCTS",
    GET_ONE_PRODUCT: "GET_ONE_PRODUCT",
    GET_CATEGORIES: "GET_CATEGORIES",
};

export const CLIENTS_ACTIONS = {
    GET_CLIENTS: 'GET_CLIENTS',
    GET_ONE_CLIENT: 'GET_ONE_CLIENT',
}